### ISSUE TITLE
Make it suitable for all generic CH56x development boards

### ISSUE THREAD

**Issue by hansfbaier** [hydrausb3/wch-ch56x-bsp#1]
It would be nice to make the BSP suitable for all CH56x
boards (like the official development board),
and enable the Hydrabus-specific parts with a compiler define.

**Comment by bvernoux** [comment]
What should be done
- [ ] Refactor  [CH56x_hydrausb3.c](https://github.com/hydrausb3/wch-ch56x-bsp/blob/main/drv/CH56x_hydrausb3.c) / [CH56x_hydrausb3.h](https://github.com/hydrausb3/wch-ch56x-bsp/blob/main/drv/CH56x_hydrausb3.h)
   - [ ] hydrausb3_gpio_cfg() to be renamed bsp_gpio_cfg() and moved to [CH56x_bsp.c](https://github.com/hydrausb3/wch-ch56x-bsp/blob/main/drv/CH56x_bsp.c) & [CH56x_bsp.h](https://github.com/hydrausb3/wch-ch56x-bsp/blob/main/drv/CH56x_bsp.h)
   - [ ] hydrausb3_gpio_read() to be renamed bsp_gpio_read() and moved to [CH56x_bsp.c](https://github.com/hydrausb3/wch-ch56x-bsp/blob/main/drv/CH56x_bsp.c) & [CH56x_bsp.h](https://github.com/hydrausb3/wch-ch56x-bsp/blob/main/drv/CH56x_bsp.h)
   - [ ] hydrausb3_gpio_set() to be renamed bsp_gpio_set() and moved to [CH56x_bsp.c](https://github.com/hydrausb3/wch-ch56x-bsp/blob/main/drv/CH56x_bsp.c) & [CH56x_bsp.h](https://github.com/hydrausb3/wch-ch56x-bsp/blob/main/drv/CH56x_bsp.h)
   - [ ] hydrausb3_gpio_clr() to be renamed bsp_gpio_clr() and moved to [CH56x_bsp.c](https://github.com/hydrausb3/wch-ch56x-bsp/blob/main/drv/CH56x_bsp.c) & [CH56x_bsp.h](https://github.com/hydrausb3/wch-ch56x-bsp/blob/main/drv/CH56x_bsp.h)
   - [ ] hydrausb3_sync2boards() to be renamed bsp_sync2boards() and moved to [CH56x_bsp.c](https://github.com/hydrausb3/wch-ch56x-bsp/blob/main/drv/CH56x_bsp.c) & [CH56x_bsp.h](https://github.com/hydrausb3/wch-ch56x-bsp/blob/main/drv/CH56x_bsp.h)
- [ ] Create HAL header for the `bsp` at root of wch-ch56x-bsp
   - [ ] Create HAL 
- [ ] Create a directory `bsp` at root of wch-ch56x-bsp repository and move files [CH56x_hydrausb3.c](https://github.com/hydrausb3/wch-ch56x-bsp/blob/main/drv/CH56x_hydrausb3.c) / [CH56x_hydrausb3.h](https://github.com/hydrausb3/wch-ch56x-bsp/blob/main/drv/CH56x_hydrausb3.h) to it

**Comment by bvernoux** [comment]
Tell me if you see something which is missing then we can close this issue

**Comment by hansfbaier** [comment]
Great work! Let's close it for now, and reopen if I stumble across anything.
